### ISSUE TITLE
System Testing

### ISSUE THREAD

**Issue by HSGamer** [etases/edu-block-client#3]
# Description
Create manual & automatic test cases for the Frontend - Backend system.

# Tasks
* [ ] Create manual tests
* [ ] Create automatic tests
* [ ] Create test reports
* [ ] Complete test reports

# Note
* May use [Selenium](https://www.selenium.dev/) to make automatic testing
* May require #1 & #2 to start
